kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dctm-cmis-pod-reader
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - watch
      - list