apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    {{- include "dctm-cmis.custom-labels" . | indent 4 }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - name: http
      targetPort: 8080
      port: {{ .Values.httpPort }}
    - name: https
      targetPort: 8443
      port: {{ .Values.httpsPort }}
  selector:
    {{- include "dctm-cmis.custom-labels" .  | indent 4 }}